sub = []
lista = []
valor1 = int(input('Digite o valor na posição [0,0]'))
sub.append(valor1)
valor2 = int(input('Digite o valor na posição [0,1]'))
sub.append(valor2)
valor3 = int(input('Digite o valor na posição [0,2]'))
sub.append(valor3)
valor4 = int(input('Digite o valor na posição [1,0]'))
sub.append(valor4)
valor5 = int(input('Digite o valor na posição [1,1]'))
sub.append(valor5)
valor6 = int(input('Digite o valor na posição [1,2]'))
sub.append(valor6)
valor7 = int(input('Digite o valor na posição [2,0]'))
sub.append(valor7)
valor8 = int(input('Digite o valor na posição [2,1]'))
sub.append(valor8)
valor9 = int(input('Digite o valor na posição [2,2]'))
sub.append(valor9)
lista.append(sub[:])
lista.clear()
print(lista)