times = ('America-MG', 'Athletico-PR', 'Atletico-GO', 'Atletico-MG', 'Avai', 'Botafogo', 'Bragantino', 'Ceara', 'Corinthians', 'Curitiba', 'Cuiaba', 'Flamengo', 'Fluminense', 'Goias', 'Internacioanal', 'Juventude', 'Palmeiras', 'Santos', 'Sao Paulo')
print(f'Os time são {times}')
print('\033[1m-=\033[m' * 15)
print(f'Os 5 primeiros colocados foram {times[0:5]}')
print('\033[1m-=\033[m' * 15)
print(f'O 4 Ultimos colocados foram {times[15:]}')
print('\033[1m-=\033[m' * 15)
print(f'Os times em ordem alfabética {sorted(times)}')
print('\033[1m-=\033[m' * 15)
print(f'O flamengo está na posição {times.index("Flamengo") + 1}° posição')
